// export const metadata = {
//   title: "Login",
//   description: "Generated By Mr.K",
// };

const Page = () => {
  return (
    <div>
      <h1>This is login page.</h1>
    </div>
  );
};

export default Page;
